// Canonical list of academic departments -- kept in exact sync with the
// website's src/lib/departments.ts. Employers pick one when posting a job
// (web-only); students pick their own here. Exact string matches between a
// job's department and a student's courseOfStudy drive the default
// (unsearched) feed scoping server-side -- see GET /api/jobs.
export const DEPARTMENTS = [
  'Computer Science',
  'Software Engineering',
  'Information Technology',
  'Cybersecurity',
  'Electrical/Electronic Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Petroleum Engineering',
  'Mechatronics Engineering',
  'Architecture',
  'Estate Management',
  'Quantity Surveying',
  'Building Technology',
  'Urban and Regional Planning',
  'Accounting',
  'Banking and Finance',
  'Business Administration',
  'Marketing',
  'Economics',
  'Actuarial Science',
  'Mass Communication',
  'Law',
  'Medicine and Surgery',
  'Nursing Science',
  'Pharmacy',
  'Public Health',
  'Biochemistry',
  'Microbiology',
  'Industrial Chemistry',
  'Statistics',
  'Mathematics',
  'Physics',
  'Agricultural Science',
  'Food Science and Technology',
  'Human Resource Management',
  'Other',
] as const;
