/// <reference types="expo/types" />

// Normally auto-regenerated by `expo start` and gitignored, but CI runs
// `tsc --noEmit` on a fresh checkout with no dev server -- so this is
// committed here (overriding the .gitignore entry) purely to keep
// typecheck deterministic. Safe to delete locally; `expo start` recreates it.
